// Ejemplo de como mandar la data - El id no debe ser modificado porque se requiere para la asignación por estado
export const data = [
  {
    id: 'Baja California',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<div><h2 style={{ color: `#fff`, fontSize: `20px` }}>Baja California</h2><p>Prueba de contenido</p></div>',
  },
  {
    id: 'Baja California Sur',
    fill: '#afb4b9',
    stroke: '#afb4b9',
    disable: true,
    data: '<div><h2 style={{ color: `#fff`, fontSize: `20px` }}>Baja California Sur</h2><p>Prueba de contenido</p></div>',
  },
  {
    id: 'Coahuila',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<div><h2>Coahuila</h2><p>Prueba de contenido</p></div>',
  },
  {
    id: 'Chihuahua',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Durango',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Sinaloa',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Sonora',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Zacatecas',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Nuevo León',
    fill: '#afb4b9',
    stroke: '#080808',
    disable: true,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'San Luis Potosí',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Tamaulipas',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Aguascalientes',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Colima',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Jalisco',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Michoacán',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Nayarit',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Campeche',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Oaxaca',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido 333</p>',
  },
  {
    id: 'Puebla',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Tabasco',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Tlaxcala',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'CDMX',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Guanajuato',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Guerrero',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Hidalgo',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Estado de México',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Morelos',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Querétaro',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Veracruz',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Chiapas',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Quintana Roo',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
  {
    id: 'Yucatán',
    fill: '#ff7e33',
    stroke: '#080808',
    disable: false,
    data: '<p>Prueba de contenido</p>',
  },
];
